name: vitepress App CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i


      - name: Build project
        run: npm run docs:build

      - name: Deploy
        if: success()
        run: echo "Deploying your React app..."